# Generated by Django 4.2.5 on 2023-09-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halaman_awal', '0003_alter_post_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img')),
                ('titleImage', models.CharField(max_length=256)),
                ('descImage', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='post',
            new_name='aboutus',
        ),
    ]
