# Generated by Django 4.2.5 on 2023-09-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halaman_awal', '0004_slider_rename_post_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='sliders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleImage', models.CharField(max_length=256)),
                ('image', models.ImageField(upload_to='static/img')),
                ('descImage', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='slider',
        ),
    ]
