# Generated by Django 4.2.5 on 2023-10-01 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halaman_awal', '0005_sliders_delete_slider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='sliders',
            options={'managed': False},
        ),
    ]
