# Generated by Django 4.2.5 on 2023-10-01 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halaman_awal', '0006_alter_aboutus_options_alter_sliders_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='aboutus',
            table='halaman_awal_aboutus',
        ),
        migrations.AlterModelTable(
            name='sliders',
            table='halaman_awal_sliders',
        ),
    ]
