# Generated by Django 4.2.5 on 2023-10-01 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halaman_awal', '0007_alter_aboutus_table_alter_sliders_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sliders',
            options={},
        ),
    ]
