# Generated by Django 4.2.5 on 2023-10-01 11:28

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halaman_awal', '0008_alter_sliders_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliders',
            name='colorBackground',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='color'),
        ),
        migrations.AlterModelTable(
            name='sliders',
            table=None,
        ),
    ]
