# Generated by Django 4.2.5 on 2023-10-01 11:44

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halaman_awal', '0009_sliders_colorbackground_alter_sliders_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliders',
            name='colorBackground',
            field=colorfield.fields.ColorField(blank=True, default='', image_field='image', max_length=25, samples=None),
        ),
    ]
