# Generated by Django 4.2.5 on 2023-10-01 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halaman_awal', '0010_alter_sliders_colorbackground'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={},
        ),
    ]
