# Generated by Django 4.2.5 on 2023-10-01 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halaman_awal', '0012_alter_aboutus_options_alter_sliders_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sliders',
            options={},
        ),
    ]
