# Generated by Django 4.2.5 on 2023-10-04 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halaman_awal', '0018_footers_link_blibli_footers_link_ig_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footers',
            old_name='link_ig',
            new_name='link_instagram',
        ),
        migrations.RenameField(
            model_name='footers',
            old_name='link_tokped',
            new_name='link_tokopedia',
        ),
    ]
